"""add payload to processed webhook events

Revision ID: 52d304959781
Revises: 66e92f7a4de5
Create Date: 2026-09-20 22:00:35.633157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '52d304959781'
down_revision: Union[str, Sequence[str], None] = '66e92f7a4de5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_webhook_events', sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_webhook_events', 'payload')
    # ### end Alembic commands ###
