"""initial metering schema

Revision ID: 813189c9eef7
Revises: 
Create Date: 2026-09-20 05:19:59.449958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '813189c9eef7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plans',
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('api_call_limit', sa.Integer(), nullable=False),
    sa.Column('token_limit', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('plan_code', sa.String(length=32), server_default='free', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_code'], ['plans.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usage_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('api_call', 'ai_tokens')", name='ck_usage_events_kind'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_usage_events_tenant_key')
    )
    op.create_index('ix_usage_events_tenant_created', 'usage_events', ['tenant_id', 'created_at'], unique=False)
    op.create_table('usage_event_items',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.CheckConstraint("metric IN ('api_calls', 'input_tokens', 'cached_input_tokens', 'output_tokens', 'reasoning_tokens')", name='ck_usage_event_items_metric'),
    sa.CheckConstraint('quantity >= 0', name='ck_usage_event_items_nonneg'),
    sa.ForeignKeyConstraint(['event_id'], ['usage_events.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'metric', name='uq_usage_event_items_metric')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usage_event_items')
    op.drop_index('ix_usage_events_tenant_created', table_name='usage_events')
    op.drop_table('usage_events')
    op.drop_table('tenants')
    op.drop_table('plans')
    # ### end Alembic commands ###
