"""add cost_uusd to usage_events

Revision ID: c0366ea95bad
Revises: 813189c9eef7
Create Date: 2026-09-20 19:10:24.780714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0366ea95bad'
down_revision: Union[str, Sequence[str], None] = '813189c9eef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_event_items_event'), table_name='usage_event_items')
    op.add_column('usage_events', sa.Column('cost_uusd', sa.BigInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usage_events', 'cost_uusd')
    op.create_index(op.f('ix_usage_event_items_event'), 'usage_event_items', ['event_id'], unique=False)
    # ### end Alembic commands ###
